import random

keyabc = ["A", "a", "Ä", "ä", "B", "b", "C", "c", "D", "d", "E", "e", "F", "f", "G", "g", "H", "h", "I", "i", "J", "j", "K", "k", "M", "m", "N", "n", "O", "o", "Ö", "ö", "P", "p", "Q", "q", "R", "r", "S", "s", "T", "t", "U", "u", "Ü", "ü", "V", "v", "W", "w", "X", "x", "Y", "y", "Z", "z"]
keysym = ["!", "@", "#", "$", "€", "%", "&", "*", "^", "°"]
print("Passgen by ClarigeClara\n2023 ClarigeClara\nVersion 1.0.0\nhttps://github.com/ClarigeClara/Password-gen\n\n\n")
print("Hier sind einige Passwörter als Vorschlag:")
print('''
Vorschlag No.   Passwörter mit 35 Zeichen
---------------------------------------------------''')
print(f"#     1         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     2         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     3         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     4         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     5         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     6         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     7         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     8         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     9         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#    10         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print('''

Vorschlag No.   Passwörter mit 23 Zeichen
---------------------------------------------------''')
print(f"#     1         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     2         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     3         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     4         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     5         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     6         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     7         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     8         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#     9         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
print(f"#    10         {random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}-{random.choice(keyabc)}{random.choice(keyabc)}{random.choice(keysym)}{random.choice(keyabc)}{random.choice(keyabc)}")
